# Use the official Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /usr/src/app

# Copy Python file
COPY app.py .

# Set default command to run the Python script
CMD ["python", "app.py"]